In [2]:
  #criação dos arrays
  import numpy as np

  x = np.array([[1, 2], [3, 4]])
  y = np.array([1.5, 3.5])
  print("x: \n", x)
  print("y: \n", y)

  

x: 
 [[1 2]
 [3 4]]
y: 
 [1.5 3.5]


In [3]:
#comparações ponto a ponto

print("Comparação de um array com um escalar (>): \n", x > 2)
print("Comparação de um array com um escalar (>=): \n", x >=2)
print("Comparação de um array com um escalar (<): \n", x < 2)
print("Comparação de um array com um escalar (<=): \n", x <= 2)
print("Comparação entre arrays (==): \n", x == x)
print("Comparação entre arrays (>): \n", x == x)
print("Comparação entre arrays (>): \n", x > y) #broadcasting



Comparação de um array com um escalar (>): 
 [[False False]
 [ True  True]]
Comparação de um array com um escalar (>=): 
 [[False  True]
 [ True  True]]
Comparação de um array com um escalar (<): 
 [[ True False]
 [False False]]
Comparação de um array com um escalar (<=): 
 [[ True  True]
 [False False]]
Comparação entre arrays (==): 
 [[ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[False False]
 [ True  True]]


In [4]:
#indexação boleana

x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])
print("x:\n", x) 

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [5]:
#indexão booleana: retornar o número de elementos maiores que k

k = 10
cond = x > k
print("condição: \n", cond)
print(f"elementos maiores que {k}:", x[cond])
# print(f"número de emlementos maiores que {k}:", len(x[cond]))

condição: 
 [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10: [11 21 42]
