In [6]:
#indexacao de arrays
#onde n é o tamanho da dimensão
import numpy as np

x=np.linspace(start=10, stop=100, num=10)
print("x:", x)
print("shape:", x.shape)

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [8]:
#extração de elementos

print("x:", x)
print("primeiro elemento:", x[0])
print("Segundo elemento:", x[1])
print("último elemento:", x[9])
print("último elemento:",x[-1])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento: 10.0
Segundo elemento: 20.0
último elemento: 100.0
último elemento: 100.0


In [10]:
#slicing: extração de subrrays:

print("x:", x)
print("dois primeiros elementos:", x[0:2]) #2 é exclusivo
print("dois primiros elementos:", x[:2]) #do inicio ate o indice 2-1
print("dois últimos elementos:", x[-2:]) #acessando os dois ultimos elementos e o resto ate o final sendo omitido
print("dois últimos elementos:", x[8:])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos: [10. 20.]
dois primiros elementos: [10. 20.]
dois últimos elementos: [ 90. 100.]
dois últimos elementos: [ 90. 100.]


In [12]:
#slicing em arrays 2d(matrizes)

x= x.reshape(2, 5) #reshape se x para 2 linhas e 5 colunas 
print("x:\n", x)

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [13]:
#extração de elementos

print("A primeira linha, segunda coluna:", x[0, 1])
print("segunda linha, pnultima coluna:", x[1, -2])
print("última linha, última coluna: ", x[1, 4])
print("última linha, última coluna", x[-1,-1])

A primeira linha, segunda coluna: 20.0
segunda linha, pnultima coluna: 90.0
última linha, última coluna:  100.0
última linha, última coluna 100.0


In [17]:
#clicing extração de subarrays

print("x:\n", x)
print("\n")
print("prineira linha inteira: ", x[0, :]) #do inicio ate o fim
print("primeira linha, segunda a quarta coluna: ", x[0, 1:4]) # primeira linha segunda a quarta coluna
print("última coluna inteira:\n ", x[:, [-1]]) #colchetes para preservar as dimensões (2x2), (3x3), (4x4)




x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


prineira linha inteira:  [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna:  [20. 30. 40.]
última coluna inteira:
  [[ 50.]
 [100.]]


In [18]:
#atenção com compartilhamento de memória em subarrays!!

x =np.array([1, 2, 3])
print("x antes:", x)
y= x[:2]
y[0] = -100#alteração do valor em y altera o valor de x
print("x depois:", x)

x antes: [1 2 3]
x depois: [-100    2    3]
