**NUMPY**

In [1]:
#Importando as bibliotecas

import numpy as np

In [5]:
#CRIAÇÃO DE ARRAYS

l=[1, 2, 3]
x=np.array(l)
print("x:", x)
print("shape:", x.shape)

x: [1 2 3]
shape: (3,)


In [6]:
type(x)

numpy.ndarray

In [7]:
#criação de um array 2D: Listas aninhadas 

l=[[1, 2], [3, 4]]
x=np.array(l)
print("x: \n", x)
print("shape:", x.shape)

x: 
 [[1 2]
 [3 4]]
shape: (2, 2)


In [10]:
#array contendo apenas 0's 

dim = (3, 3) #linhas, colunas

x= np.zeros(dim)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (3, 3)


In [11]:
#array contendo apenas 1's

size =(2, 2) #linhas/colunas
x = np.ones(size)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[1. 1.]
 [1. 1.]]
shape: (2, 2)


In [13]:
#criação de valores dentero de um intervalo
#valores uniformes entre 5 e 15

x_min, x_max = 5,15
x=np.linspace(start=x_min, stop =x_max, num=6)
print("x:",x)
print("shape:", x.shape)

x: [ 5.  7.  9. 11. 13. 15.]
shape: (6,)
