In [2]:
#criação de dois arrays x e y

import numpy as np

x=np.ones((2,2))
y=np.eye(2)
print("x: \n", x)
print("y: \n", y)



x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [4]:
#soma 
print("soma de dois arrays: \n", x+y)
print("soma com float/int:\n", x+2.) #broadcasting(possivel somar com outros tipos de elementos)

soma de dois arrays: 
 [[2. 1.]
 [1. 2.]]
soma com float/int:
 [[3. 3.]
 [3. 3.]]


In [5]:
#subtração
print("subtração de dois arrays:\n", x-y)
print("subtração com float/int:\n", x - 2) #broadcasting

subtração de dois arrays:
 [[0. 1.]
 [1. 0.]]
subtração com float/int:
 [[-1. -1.]
 [-1. -1.]]


In [6]:
#divisão

print("divisão de dois arrays:\n", x/y)
print("divisão com float/int:\n", x/2)

divisão de dois arrays:
 [[ 1. inf]
 [inf  1.]]
divisão com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [7]:
#soma, subtração e divisão

print("Combinação de operadores: \n", (x+y)/(x-2))

Combinação de operadores: 
 [[-2. -1.]
 [-1. -2.]]


In [8]:
#Multiplicação

print("multiplicação de dois arrays:\n", x * y)
print("multiplicação com float/int:\n", x * 2) #broadcasting

multiplicação de dois arrays:
 [[1. 0.]
 [0. 1.]]
multiplicação com float/int:
 [[2. 2.]
 [2. 2.]]


In [9]:
#criar arrays costumizados

5 * np.ones((10, 10))

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [12]:
#definição do problema

A = np.array([[1, 2], [3, -2]])
c = np.array([[7], [-11]])
print("A: \n", A)
print("c: \n", c)

A: 
 [[ 1  2]
 [ 3 -2]]
c: 
 [[  7]
 [-11]]


In [16]:
#Sistemas de equações

#solução

#np.linalg é um conjunto de metodos para trabalhar com algebra linear
# x = np.dot(np.linalg.inv(A), c)
x = np.linalg.inv(A) @ c #solução usando o operador @ do próprio python q multiplica matrizes
print("(a, b):", x.ravel())

(a, b): [-1.  4.]
